name: Run base_url.py script

on:
  schedule:
    - cron: '0 * * * *'  # Bu işlem her saat başı çalışacak. Zamanı ihtiyaca göre ayarlayabilirsiniz.
  workflow_dispatch:  # Manuel çalıştırma için

jobs:
  run_base_url_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Python sürümünü istediğiniz gibi ayarlayabilirsiniz

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run base_url.py
        run: |
          python base_url.py  # base_url.py dosyasını çalıştır

      - name: Commit and push changes if base_url.txt was updated
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add base_url.txt
          git diff --exit-code || (git commit -m "Update base_url.txt" && git push)
