name: Keep Proxy Alive 2 URL
 
on:
  schedule:
    - cron: "30 */4 * * *"

  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: 5 saat boyunca her 10 dakikada bir ping at ve cache ping
        env:
          PING_URL1: ${{ secrets.PING_URL1 }}
          PING_URL2: ${{ secrets.PING_URL2 }}
          PING_CACHE_URL1: ${{ secrets.PING_CACHE_URL1 }}
          PING_CACHE_URL2: ${{ secrets.PING_CACHE_URL2 }}
        run: |
          END_TIME=$((SECONDS + 5 * 60 * 60))

          while [ $SECONDS -lt $END_TIME ]; do
            echo "⏰ Yeni ping turu başlıyor: $(date '+%Y-%m-%d %H:%M:%S')"

            # 🔄 Normal pingler
            for i in 1 2; do
              VAR="PING_URL$i"
              URL="${!VAR:-}"
              if [[ -n "$URL" ]]; then
                LABEL="$VAR"
                echo "🔄 Yeni ping atılıyor -> $LABEL"
                HTML=$(curl -s "$URL")
                TEXT=$(echo "$HTML" | grep -oP '(?<=<h1>).*?(?=</h1>)')

                if [[ -z "$TEXT" ]]; then
                  echo "❌ Sistem pasif olabilir! ($LABEL)"
                else
                  echo "✅ $TEXT ($LABEL)"
                fi
              fi
            done

            # 🔄 Cache pingler
            for j in 1 2; do
              VAR="PING_CACHE_URL$j"
              CACHE_URL="${!VAR:-}"
              if [[ -n "$CACHE_URL" ]]; then
                LABEL="$VAR"
                echo "🔄 Cache ping atılıyor -> $LABEL"
                CACHE_HTML=$(curl -s "$CACHE_URL")
                CACHE_TEXT=$(echo "$CACHE_HTML" | jq -r '.message')

                if [[ -z "$CACHE_TEXT" || "$CACHE_TEXT" == "null" ]]; then
                  echo "❌ Cache sistemi pasif olabilir! ($LABEL)"
                else
                  echo "✅ Cache: $CACHE_TEXT ($LABEL)"
                fi
              fi
            done

            echo "⏳ 10 dakika bekleniyor..."
            sleep 600
          done

          echo "✅ 5 saatlik tüm pingler tamamlandı."
