name: Keep Proxy Alive

on:
  schedule:
    - cron: "30 */4 * * *"    

  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: 5 saat boyunca her 10 dakikada bir ping at ve en sonunda cache ping at
        env:
          PING_URL: ${{ secrets.PING_URL }}
          PING_CACHE_URL: ${{ secrets.PING_CACHE_URL }}
        run: |
          END_TIME=$((SECONDS + 5 * 60 * 60))

          while [ $SECONDS -lt $END_TIME ]; do
            echo "🔄 Yeni ping atılıyor: $(date '+%Y-%m-%d %H:%M:%S')"
            HTML=$(curl -s "$PING_URL")
            TEXT=$(echo "$HTML" | grep -oP '(?<=<h1>).*?(?=</h1>)')

            if [[ -z "$TEXT" ]]; then
              echo "❌ Sistem pasif olabilir!"
            else
              echo "✅ $TEXT"
            fi

            echo "⏳ 10 dakika bekleniyor..."
            sleep 600
          done

          echo "✅ 5 saatlik çalışma tamamlandı."

          # En son sadece 1 kere PING_CACHE_URL'e ping at
          echo "🔄 Cache ping atılıyor: $(date '+%Y-%m-%d %H:%M:%S')"
          CACHE_HTML=$(curl -s "$PING_CACHE_URL")
          CACHE_TEXT=$(echo "$CACHE_HTML" | grep -oP '(?<=<h1>).*?(?=</h1>)')

          if [[ -z "$CACHE_TEXT" ]]; then
            echo "❌ Cache sistemi pasif olabilir!"
          else
            echo "✅ Cache: $CACHE_TEXT"
          fi
